//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMashAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codemash
    {
        public int id { get; set; }
        public int codemashid { get; set; }
    }
}
